# Generated by Django 4.1.3 on 2022-11-13 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_usersubscription_cardnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='pay_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
