# Generated by Django 4.1.3 on 2022-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_userpayments_paid_usersubscription_cardnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='next_pay',
            field=models.DateField(null=True),
        ),
    ]
