# Generated by Django 4.1.3 on 2022-11-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_userpayments_username_usersubscription_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='expiry',
            field=models.PositiveIntegerField(default=0.0004945598417408506, help_text='Enter as MMYY'),
            preserve_default=False,
        ),
    ]
