# Generated by Django 4.1.3 on 2022-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_userpayments_expiry_userpayments_next_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='renew',
            field=models.BooleanField(default=True),
        ),
    ]
