# Generated by Django 4.1.3 on 2022-12-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_usersubscription_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='amount',
            field=models.FloatField(),
        ),
    ]
