# Generated by Django 4.1.3 on 2022-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_userpayments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriptionplan',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubcriptionPlanFeatures',
        ),
    ]
