# Generated by Django 4.1.3 on 2022-12-12 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_subcriptionplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='pay_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
