# Generated by Django 4.1.3 on 2022-12-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_userpayments_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expiry',
            field=models.CharField(help_text='Enter as MMYY', max_length=100),
        ),
    ]
