# Generated by Django 4.1.3 on 2022-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
