# Generated by Django 4.1.3 on 2022-12-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='quantity',
        ),
    ]
