# Generated by Django 4.1.3 on 2022-11-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_user', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='classes.class')),
            ],
        ),
    ]
