# Generated by Django 4.1.3 on 2022-11-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_recurrences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='recurrences',
            new_name='time',
        ),
    ]
