# Generated by Django 4.1.3 on 2022-11-13 07:18

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_recurrences_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
