# Generated by Django 4.1.3 on 2022-11-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
