# Generated by Django 4.1.3 on 2022-11-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_rename_end_class_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='classes.class'),
            preserve_default=False,
        ),
    ]
