# Generated by Django 4.1.3 on 2022-11-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_event_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='studio',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='studio',
            new_name='classes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
    ]
