# Generated by Django 4.1.3 on 2022-11-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_distance'),
        ('classes', '0008_rename_studio_event_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='studios.studio'),
            preserve_default=False,
        ),
    ]
