# Generated by Django 4.1.3 on 2022-11-13 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0014_remove_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
