# Generated by Django 4.1.3 on 2022-11-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_event_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='current_user',
        ),
    ]
